# load antigen zsh plugin manager
source .dotfiles/submodules/antigen/antigen.zsh

# load the oh-my-zsh's library.
antigen use oh-my-zsh

# bundles from the default repo (robbyrussell's oh-my-zsh)
antigen bundle brew
antigen bundle bgnotify
antigen bundle command-not-found
antigen bundle docker
antigen bundle fasd
antigen bundle git
antigen bundle git-extras
antigen bundle gradle
antigen bundle mvn
antigen bundle osx
antigen bundle pip
antigen bundle ssh-agent
antigen bundle sublime
antigen bundle sudo
antigen bundle web-search

# bundles from other repos
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle Lokaltog/powerline powerline/bindings/zsh # powerline shell

# custom bundles
antigen bundle $HOME/.dotfiles/zsh/