# load zgen
source "${HOME}/.dotfiles/submodules/zgen/zgen.zsh"

# check if there's no init script
# zgen configuration
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    # plugins
    zgen oh-my-zsh plugins/brew
    zgen oh-my-zsh plugins/bgnotify
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh plugins/docker
    zgen oh-my-zsh plugins/fasd
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/git-extras
    zgen oh-my-zsh plugins/gpg-agent
    zgen oh-my-zsh plugins/gradle
    zgen oh-my-zsh plugins/mvn
    zgen oh-my-zsh plugins/osx
    zgen oh-my-zsh plugins/pip
    zgen oh-my-zsh plugins/ssh-agent
    zgen oh-my-zsh plugins/sublime
    zgen oh-my-zsh plugins/sudo
    zgen oh-my-zsh plugins/web-search

    # bundles from other repos
    zgen load Tarrasch/zsh-bd bd.plugin.zsh
    zgen load zsh-users/zsh-completions src
    zgen load zsh-users/zsh-syntax-highlighting zsh-syntax-highlighting.plugin.zsh
    zgen load chriskempson/base16-shell base16-eighties.dark.sh # needed for powerline

    # theme
    zgen load caiogondim/bullet-train-oh-my-zsh-theme bullet-train.zsh-theme

    # save all to init script
    zgen save
fi

# Load all files from .dotfiles/zsh/ directory
if [ -d $HOME/.dotfiles/zsh ]; then
  for file in $HOME/.dotfiles/zsh/*.zsh; do
    source $file
  done
fi
